runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
- url: /static
  static_dir: static

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
